spring:
  ai:
    vectorstore:
      pgvector:
        dimensions: 3072
        table-name: vector_store
        schema-name: public
        schema-validation: true
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-large
  jackson:
    mapper:
      accept-case-insensitive-enums: true
anthropic:
  api-key: ${ANTHROPIC_API_KEY}

