spring:
  ai:
    vectorstore:
      pgvector:
        dimensions: 3072
        table-name: vector_store
        schema-name: public
        schema-validation: true
    openai:
      api-key: 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
      embedding:
        options:
          model: text-embedding-3-large
anthropic:
  api-key: ***REMOVED-ANTHROPIC-API-KEY***

