include:
  - docker-ml.yml

services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 10s
      timeout: 5s
      start_period: 2s
      retries: 5
    restart: on-failure
volumes:
  pgdata: