spring:
  datasource:
    url: jdbc:postgresql://***REMOVED-HOST***:5444/mydatabase?options=-c%20TimeZone%3DEurope/Kyiv
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ***REMOVED-HOST***
      port: 6379
      password: ***REMOVED-VALKEY-PASSWORD***

restate:
  client:
    baseUri: http://***REMOVED-HOST***:9080
  sdk:
    http:
      port: 9081

rorm:
  ml:
    cluster: MlInfraStack-MlCluster87EBA3AE-k1zgJGFRBWkS
    service: MlInfraStack-MlServiceAC8BC53F-R1WsD6iG3HoP
    restateAdminUrl: http://***REMOVED-HOST***:9070
    restateEndpointUrl: https://unsiding-sparrowless-chaya.ngrok-free.dev
    valkeyUrl: redis://:***REMOVED-VALKEY-PASSWORD***@***REMOVED-HOST***:6379
    durable-execution: true
    serviceBaseUrl: http://MlInfr-MlAlb-fsf84yGJ69Ex-1790046904.eu-central-1.elb.amazonaws.com
