spring:
  datasource:
    url: jdbc:postgresql://3.75.210.208:5444/mydatabase?options=-c%20TimeZone%3DEurope/Kyiv
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 3.75.210.208
      port: 6379
      password: rorm-valkey-pass123!

restate:
  client:
    baseUri: http://3.75.210.208:9080
  sdk:
    http:
      port: 9081

rorm:
  ml:
    cluster: MlInfraStack-MlCluster87EBA3AE-k1zgJGFRBWkS
    service: MlInfraStack-MlServiceAC8BC53F-R1WsD6iG3HoP
    restateAdminUrl: http://3.75.210.208:9070
    restateEndpointUrl: http://100.69.197.31:9081
    valkeyUrl: redis://:rorm-valkey-pass123!@3.75.210.208:6379
    durable-execution: true
    serviceBaseUrl: http://MlInfr-MlAlb-fsf84yGJ69Ex-1790046904.eu-central-1.elb.amazonaws.com

anthropic:
  bedrock:
    region: us-east-1